services:
  db:
    image: postgres:17.5-alpine3.22
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.3-alpine3.21
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - SERVICES=s3
      - PERSISTENCE=1
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    build:
      context: .
      dockerfile: ./infra/dockerfiles/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - localstack
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "npx mikro-orm migration:create && npx mikro-orm migration:up && yarn start:dev"

volumes:
  postgres_data:
